name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and package container image for release

    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # image name is dumbdrop, in the docker user's repo
          # this allows the push to work in forks
          images: |
            name=ghcr.io/${{ github.repository }}

          tags: |
            # the semantic versioning tags add "latest" when a version tag is present
            # output x.y.z, based on a tag vx.y.z (e.g. 1.1.2 for a tag v1.1.2)
            type=semver,pattern={{version}}
            # output x.y, based on a tag vx.y.z
            type=semver,pattern={{major}}.{{minor}}
            # output x, based on a tag vx.y.z, disabled if x is zero
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            # full length sha
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
